# Generated by Django 5.2.8 on 2025-11-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('orthopedics', 'Orthopedics'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics')], max_length=50),
        ),
    ]
